name: ksql
lang: unknown
codeowners:
  enable: true
semaphore:
  enable: true
  pipeline_type: cp
  downstream_projects: ["confluent-security-plugins", "confluent-cloud-plugins", "cc-docker-ksql"]
  extra_deploy_args: '-Ddocker.skip=true'
  extra_build_args: "-Dmaven.gitcommitid.nativegit=true -DskipTests -DskipIntegrationTests"
  maven_build_goals: "clean install"
